//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "oidc_provider_issued_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub record_id: i32,
    pub token_uid: String,
    pub access_token: String,
    pub refresh_token: String,
    pub grant_client_id: String,
    pub grant_owner_id: String,
    pub grant_scope: String,
    pub grant_redirect_uri: String,
    pub grant_until: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
