//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use crate::domain::oidc::registrar::domain::OidcClientType;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "oidc_provider_registrar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub record_id: i32,
    pub client_id: String,
    pub client_type: OidcClientType,
    pub default_scope: String,
    pub redirect_uri: String,
    pub provider_uid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
