//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::oidc_provider_grants::Entity as OidcProviderGrants;
pub use super::oidc_provider_issued_tokens::Entity as OidcProviderIssuedTokens;
pub use super::oidc_provider_registrar::Entity as OidcProviderRegistrar;
