//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mee_network_persona_model_schemas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub schema_id: i32,
    pub schema_uid: String,
    pub schema_definition: String,
    pub user_meeid: String,
    pub provider_meeid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
