//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_user_id: i64,
    #[sea_orm(unique)]
    pub mdn_user_uid: String,
    #[sea_orm(unique)]
    pub mdn_user_email: String,
    #[sea_orm(unique)]
    pub mdn_user_phone: Option<String>,
    pub mdn_user_name: String,
    pub mdn_user_role: String,
    pub mdn_user_created_at: DateTimeWithTimeZone,
    pub is_user_active: bool,
    pub is_user_verified: bool,
    pub salt: String,
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mdn_context_scoped_ids::Entity")]
    MdnContextScopedIds,
    #[sea_orm(
        has_many = "super::mdn_custodian_context_data_access_caps::Entity"
    )]
    MdnCustodianContextDataAccessCaps,
    #[sea_orm(
        has_many = "super::mdn_custodian_context_operation_caps::Entity"
    )]
    MdnCustodianContextOperationCaps,
    #[sea_orm(has_many = "super::mdn_custodians::Entity")]
    MdnCustodians,
    #[sea_orm(has_many = "super::mdn_user_signing_pub_keys::Entity")]
    MdnUserSigningPubKeys,
}

impl Related<super::mdn_context_scoped_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnContextScopedIds.def()
    }
}

impl Related<super::mdn_custodian_context_data_access_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianContextDataAccessCaps.def()
    }
}

impl Related<super::mdn_custodian_context_operation_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianContextOperationCaps.def()
    }
}

impl Related<super::mdn_custodians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodians.def()
    }
}

impl Related<super::mdn_user_signing_pub_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUserSigningPubKeys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
