//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_identity_contexts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_identity_context_id: i64,
    #[sea_orm(unique)]
    pub mdn_identity_context_uid: String,
    pub willow_namespace_id: String,
    pub context_scoped_subject_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_context_scoped_ids::Entity",
        from = "Column::ContextScopedSubjectId",
        to = "super::mdn_context_scoped_ids::Column::MdnContextScopedId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnContextScopedIds,
    #[sea_orm(
        has_many = "super::mdn_custodian_context_data_access_caps::Entity"
    )]
    MdnCustodianContextDataAccessCaps,
    #[sea_orm(has_many = "super::mdn_identity_contexts_in_storages::Entity")]
    MdnIdentityContextsInStorages,
}

impl Related<super::mdn_context_scoped_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnContextScopedIds.def()
    }
}

impl Related<super::mdn_custodian_context_data_access_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianContextDataAccessCaps.def()
    }
}

impl Related<super::mdn_identity_contexts_in_storages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnIdentityContextsInStorages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
