//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "sda_profiles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub record_id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub record_uid: String,
    #[sea_orm(column_type = "Text")]
    pub user_uid: String,
    #[sea_orm(column_type = "Text")]
    pub sda_profile: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
