//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_custodians")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_custodian_id: i64,
    #[sea_orm(unique)]
    pub mdn_custodian_uid: String,
    pub mdn_user_custodian_id: Option<i64>,
    pub mdn_provider_custodian_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mdn_context_scoped_ids::Entity")]
    MdnContextScopedIds,
    #[sea_orm(
        has_many = "super::mdn_custodian_context_data_access_caps::Entity"
    )]
    MdnCustodianContextDataAccessCaps,
    #[sea_orm(
        has_many = "super::mdn_custodian_context_operation_caps::Entity"
    )]
    MdnCustodianContextOperationCaps,
    #[sea_orm(has_many = "super::mdn_node_hosting_platforms::Entity")]
    MdnNodeHostingPlatforms,
    #[sea_orm(has_many = "super::mdn_nodes::Entity")]
    MdnNodes,
    #[sea_orm(
        belongs_to = "super::mdn_providers::Entity",
        from = "Column::MdnProviderCustodianId",
        to = "super::mdn_providers::Column::MdnProviderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnProviders,
    #[sea_orm(
        belongs_to = "super::mdn_users::Entity",
        from = "Column::MdnUserCustodianId",
        to = "super::mdn_users::Column::MdnUserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnUsers,
}

impl Related<super::mdn_context_scoped_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnContextScopedIds.def()
    }
}

impl Related<super::mdn_custodian_context_data_access_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianContextDataAccessCaps.def()
    }
}

impl Related<super::mdn_custodian_context_operation_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianContextOperationCaps.def()
    }
}

impl Related<super::mdn_node_hosting_platforms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodeHostingPlatforms.def()
    }
}

impl Related<super::mdn_nodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodes.def()
    }
}

impl Related<super::mdn_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnProviders.def()
    }
}

impl Related<super::mdn_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
