//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_user_device_replication_capabilities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_user_device_replication_capability_id: i32,
    pub mdn_user_id: i32,
    pub from_device_id: i32,
    pub to_device_id: i32,
    #[sea_orm(column_type = "Text")]
    pub willow_capabilities: String,
    pub expires: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_user_devices::Entity",
        from = "Column::FromDeviceId",
        to = "super::mdn_user_devices::Column::MdnUserDeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnUserDevices2,
    #[sea_orm(
        belongs_to = "super::mdn_user_devices::Entity",
        from = "Column::ToDeviceId",
        to = "super::mdn_user_devices::Column::MdnUserDeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnUserDevices1,
    #[sea_orm(
        belongs_to = "super::mdn_users::Entity",
        from = "Column::MdnUserId",
        to = "super::mdn_users::Column::MdnUserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnUsers,
}

impl Related<super::mdn_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
