//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_user_signing_pub_keys")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_user_signing_pub_key_id: i64,
    #[sea_orm(unique)]
    pub mdn_user_signing_pub_key_did: String,
    pub mdn_node_hosting_platform_id: Option<i64>,
    pub mdn_user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_node_hosting_platforms::Entity",
        from = "Column::MdnNodeHostingPlatformId",
        to = "super::mdn_node_hosting_platforms::Column::MdnNodeHostingPlatformId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnNodeHostingPlatforms,
    #[sea_orm(
        belongs_to = "super::mdn_users::Entity",
        from = "Column::MdnUserId",
        to = "super::mdn_users::Column::MdnUserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnUsers,
}

impl Related<super::mdn_node_hosting_platforms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodeHostingPlatforms.def()
    }
}

impl Related<super::mdn_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
