//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_node_caps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_node_cap_id: i64,
    #[sea_orm(unique)]
    pub mdn_node_cap_uid: String,
    pub mdn_node_willow_cap_token: String,
    pub mdn_custodian_context_data_access_cap_id: i64,
    pub mdn_identity_context_on_node_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_custodian_context_data_access_caps::Entity",
        from = "Column::MdnCustodianContextDataAccessCapId",
        to = "super::mdn_custodian_context_data_access_caps::Column::MdnCustodianContextDataAccessCapId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnCustodianContextDataAccessCaps,
    #[sea_orm(
        belongs_to = "super::mdn_identity_contexts_on_nodes::Entity",
        from = "Column::MdnIdentityContextOnNodeId",
        to = "super::mdn_identity_contexts_on_nodes::Column::MdnIdentityContextOnNodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnIdentityContextsOnNodes,
}

impl Related<super::mdn_custodian_context_data_access_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianContextDataAccessCaps.def()
    }
}

impl Related<super::mdn_identity_contexts_on_nodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnIdentityContextsOnNodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
