//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_identity_contexts_on_nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_identity_context_on_node_id: i64,
    #[sea_orm(unique)]
    pub mdn_identity_context_on_node_uid: String,
    pub mdn_identity_context_id: i64,
    pub mdn_custodian_storage_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mdn_custodian_storage_caps::Entity")]
    MdnCustodianStorageCaps,
    #[sea_orm(
        belongs_to = "super::mdn_custodian_storages::Entity",
        from = "Column::MdnCustodianStorageId",
        to = "super::mdn_custodian_storages::Column::MdnCustodianStorageId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnCustodianStorages,
    #[sea_orm(
        belongs_to = "super::mdn_identity_contexts::Entity",
        from = "Column::MdnIdentityContextId",
        to = "super::mdn_identity_contexts::Column::MdnIdentityContextId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnIdentityContexts,
}

impl Related<super::mdn_custodian_storage_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianStorageCaps.def()
    }
}

impl Related<super::mdn_custodian_storages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodianStorages.def()
    }
}

impl Related<super::mdn_identity_contexts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnIdentityContexts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
