//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_node_hosting_platforms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_node_hosting_platform_id: i64,
    #[sea_orm(unique)]
    pub mdn_node_hosting_platform_uid: String,
    pub willow_peer_id: String,
    pub iroh_node_id: String,
    pub mdn_custodian_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_custodians::Entity",
        from = "Column::MdnCustodianId",
        to = "super::mdn_custodians::Column::MdnCustodianId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnCustodians,
    #[sea_orm(has_many = "super::mdn_nodes_on_hosting_platforms::Entity")]
    MdnNodesOnHostingPlatforms,
    #[sea_orm(has_many = "super::mdn_user_signing_pub_keys::Entity")]
    MdnUserSigningPubKeys,
}

impl Related<super::mdn_custodians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnCustodians.def()
    }
}

impl Related<super::mdn_nodes_on_hosting_platforms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodesOnHostingPlatforms.def()
    }
}

impl Related<super::mdn_user_signing_pub_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUserSigningPubKeys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
