//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_user_id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub mdn_user_uid: String,
    #[sea_orm(column_type = "Text", unique)]
    pub mdn_user_email: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub mdn_user_phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub mdn_user_name: Option<String>,
    pub mdn_user_role: String,
    pub is_user_active: bool,
    pub is_user_verified: bool,
    #[sea_orm(column_type = "Text")]
    pub salt: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_many = "super::mdn_user_device_replication_capabilities::Entity"
    )]
    MdnUserDeviceReplicationCapabilities,
    #[sea_orm(
        has_many = "super::mdn_user_device_requests_for_linkage::Entity"
    )]
    MdnUserDeviceRequestsForLinkage,
    #[sea_orm(has_many = "super::mdn_user_devices::Entity")]
    MdnUserDevices,
}

impl Related<super::mdn_user_device_replication_capabilities::Entity>
    for Entity
{
    fn to() -> RelationDef {
        Relation::MdnUserDeviceReplicationCapabilities.def()
    }
}

impl Related<super::mdn_user_device_requests_for_linkage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUserDeviceRequestsForLinkage.def()
    }
}

impl Related<super::mdn_user_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUserDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
