//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_user_devices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_user_device_id: i64,
    #[sea_orm(unique)]
    pub mdn_user_device_uid: String,
    pub mdn_user_id: i64,
    pub device_description: String,
    pub is_device_linked: bool,
    pub device_did: String,
    pub willow_peer_id: String,
    pub iroh_node_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_many = "super::mdn_user_device_requests_for_linkage::Entity"
    )]
    MdnUserDeviceRequestsForLinkage,
    #[sea_orm(
        belongs_to = "super::mdn_users::Entity",
        from = "Column::MdnUserId",
        to = "super::mdn_users::Column::MdnUserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnUsers,
}

impl Related<super::mdn_user_device_requests_for_linkage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUserDeviceRequestsForLinkage.def()
    }
}

impl Related<super::mdn_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
