//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_node_signing_keys")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_node_signing_key_id: i64,
    #[sea_orm(unique)]
    pub mdn_node_signing_key_uid: String,
    pub mdn_node_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_nodes::Entity",
        from = "Column::MdnNodeId",
        to = "super::mdn_nodes::Column::MdnNodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnNodes,
}

impl Related<super::mdn_nodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
