//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mdn_identity_context_to_nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mdn_identity_context_to_node_id: i64,
    #[sea_orm(unique)]
    pub mdn_identity_context_to_node_uid: String,
    pub mdn_identity_context_id: i64,
    pub mdn_node_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mdn_identity_contexts::Entity",
        from = "Column::MdnIdentityContextId",
        to = "super::mdn_identity_contexts::Column::MdnIdentityContextId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnIdentityContexts,
    #[sea_orm(has_many = "super::mdn_node_caps::Entity")]
    MdnNodeCaps,
    #[sea_orm(
        belongs_to = "super::mdn_nodes::Entity",
        from = "Column::MdnNodeId",
        to = "super::mdn_nodes::Column::MdnNodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MdnNodes,
}

impl Related<super::mdn_identity_contexts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnIdentityContexts.def()
    }
}

impl Related<super::mdn_node_caps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodeCaps.def()
    }
}

impl Related<super::mdn_nodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MdnNodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
