//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod mdn_user_device_replication_capabilities;
pub mod mdn_user_device_requests_for_linkage;
pub mod mdn_user_devices;
pub mod mdn_users;
