//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::mdn_user_device_replication_capabilities::Entity as MdnUserDeviceReplicationCapabilities;
pub use super::mdn_user_device_requests_for_linkage::Entity as MdnUserDeviceRequestsForLinkage;
pub use super::mdn_user_devices::Entity as MdnUserDevices;
pub use super::mdn_users::Entity as MdnUsers;
