//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::domain::user::account::domain::UserRole;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mee_network_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(unique)]
    pub user_meeid: String,
    #[sea_orm(unique)]
    pub user_email: String,
    #[sea_orm(unique)]
    pub user_phone: Option<String>,
    pub user_role: UserRole,
    pub is_active: bool,
    pub salt: String,
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
