include .env

# The order matters: the database name should be overridden before including the common makefile.
PG_DATABASE_NAME=mee_user_manager_db

include ../../../mee-utils/scripts/dev.service.common.mk
