
gen_dev_mee_signature:
	cargo run --bin=keygen -- \
		--jwk-auth-signature-secret-path="dev_mee_signature" \
		--iroh-signature-secret-path="dev_iroh_signature" \
		--signatures-secret-path-test-folder="$$(pwd)/../target"