//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::advertiser_hil_application::Entity as AdvertiserHilApplication;
pub use super::pda_hil_application::Entity as PdaHilApplication;
pub use super::provider_mdn_license_application::Entity as ProviderHilApplication;
