//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::domain::provider::mdn_license_application::domain::{
    MdnLicenseApplicationStatus, ProviderMdnLicenseApplicationModel,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "provider_mdn_license_application")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(unique)]
    pub meeid: String,
    pub provider_meeid: String,
    pub contact_email: String,
    pub company_name: String,
    pub company_uri: String,
    pub cloud_node_discovery_url: String,
    pub decentralized_id: String,
    pub status: MdnLicenseApplicationStatus,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

impl From<ProviderMdnLicenseApplicationModel> for Model {
    fn from(
        ProviderMdnLicenseApplicationModel {
            meeid,
            provider_meeid,
            contact_email,
            company_name,
            company_uri,
            cloud_node_discovery_url,
            decentralized_id,
            status,
            created_at,
            updated_at,
        }: ProviderMdnLicenseApplicationModel,
    ) -> Self {
        Self {
            id: 0,
            meeid,
            provider_meeid,
            contact_email,
            company_name,
            company_uri,
            cloud_node_discovery_url,
            decentralized_id,
            status,
            created_at,
            updated_at,
        }
    }
}

impl From<Model> for ProviderMdnLicenseApplicationModel {
    fn from(val: Model) -> Self {
        ProviderMdnLicenseApplicationModel {
            meeid: val.meeid,
            provider_meeid: val.provider_meeid,
            contact_email: val.contact_email,
            company_name: val.company_name,
            company_uri: val.company_uri,
            cloud_node_discovery_url: val.cloud_node_discovery_url,
            decentralized_id: val.decentralized_id,
            status: val.status,
            created_at: val.created_at,
            updated_at: val.updated_at,
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
