//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;
use service_utils::mee_provider_manager::domain::ProviderRole;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "mee_network_providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub provider_id: i32,
    #[sea_orm(unique)]
    pub provider_meeid: String,
    #[sea_orm(unique)]
    pub provider_email: String,
    pub provider_name: String,
    pub provider_role: ProviderRole,
    pub is_active: bool,
    pub salt: String,
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::provider_cloud_nodes::Entity")]
    ProviderCloudNodes,
}

impl Related<super::provider_cloud_nodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProviderCloudNodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
