name: "Deploy Mee Network Provider on Dev"
on:
  workflow_dispatch: 

jobs:
  build:
    name: cargo build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1043231896197/locations/global/workloadIdentityPools/github-actions-pool/providers/github"
          service_account: "github-actions@the-mee-foundation.iam.gserviceaccount.com"
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
      - name: Build and push
        run: |
          docker build -t us-west1-docker.pkg.dev/the-mee-foundation/dev-repo/network-provider:latest --build-arg RUST_APP=agent_service --build-arg SECRETS_KEYGEN=dev_secrets_keygen --file ./rust.service.Dockerfile ../../.. 
          docker push us-west1-docker.pkg.dev/the-mee-foundation/dev-repo/network-provider:latest
        working-directory: ./repos/mee-network-provider/ops/docker
      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'dev-cluster'
          location: 'us-west1-c'
      - name: Restart service
        run: |
          kubectl rollout restart deployment/network-provider-mee-foundation -n services